Repository rainlab/translate-plugin, pull requests merged in 2019-05, with the labels that each got.

#454 Use translate.localePicker.translateParams in AlternateHrefLangElemets component
  components/AlternateHrefLangElements.php
Labels: Status: Completed, Type: Maintenance

#364 Preserve any query string parameters when forcing the url schema
  README.md
  components/LocalePicker.php
Labels: Status: Completed, Type: Conceptual Enhancement

#433 Add operator to where clause
  behaviors/TranslatableModel.php
Labels: Status: Response Needed, Type: Maintenance

#479 delete translation static content when parent page is deleted
  behaviors/TranslatableCmsObject.php
Labels: Status: Completed, Type: Maintenance

#419 Add ability for models to provide computed data
  behaviors/TranslatableModel.php
Labels: Status: Completed, Type: Enhancement

#486 add option to disable locale prefix routes
  config/config.php
  routes.php
Labels: Status: Testing Needed, Type: Enhancement

#483 Implement localeUrl filter
  Plugin.php
Labels: Status: Completed, Type: Enhancement
