Repository rainlab/translate-plugin, pull requests merged in 2019-12, with the labels that each got.

#529 Slovenian language added
  lang/sl/lang.php
Labels: Status: Completed, Type: Maintenance

#528 properly add translatable propertyto extended model
  Plugin.php
Labels: Type: Enhancement

#522 restore support for accessors & mutators
  behaviors/TranslatablePage.php
  classes/TranslatableBehavior.php
Labels: Status: Testing Needed, Type: Maintenance

#406 Message translation with locale argument
  Plugin.php
  README.md
  models/Message.php
Labels: Status: Review Needed, Status: Testing Needed, Type: Conceptual Enhancement
