Repository rainlab/translate-plugin, pull requests merged in 2019-04, with the labels that each got.

#458 Handle oc.inputPreset.beforeUpdate event
  assets/js/multilingual.js
Labels: Status: Completed, Type: Maintenance

#461 prevent nested field names from matching Model->translatable[] fields
  classes/EventRegistry.php
Labels: Status: Completed, Type: Maintenance

#467 Additional fixes to #466
  formwidgets/MLRepeater.php
  formwidgets/mlrepeater/assets/js/mlrepeater.js
Labels: Status: Completed, Type: Maintenance

#472 implement PurgeableBehavior
  Plugin.php
Labels: Type: Maintenance

#474 add getter for translatableOriginals array
  classes/TranslatableBehavior.php
Labels: Type: Maintenance

#470 Make FileUpload properties translatable
  Plugin.php
Labels: Status: Completed, Type: Enhancement

#452 Fix array error when extending CMS Page original translatable attributes
  behaviors/TranslatablePage.php
Labels: Type: Maintenance
