Repository rainlab/translate-plugin, pull requests merged in 2020-11, with the labels that each got.

#623 Faster version of transWhere
  behaviors/TranslatableModel.php
Labels: Status: Completed, Type: Maintenance

#621 remove redundant code (present in MLControl trait)
  formwidgets/MLRepeater.php
  formwidgets/MLText.php
  formwidgets/MLTextarea.php
Labels: Status: Review Needed, Type: Maintenance

#606 Translate json fields
  classes/TranslatableBehavior.php
Labels: Status: Review Needed, Status: Testing Needed, Type: Enhancement

#586 Fix scopeTransOrderBy duplicates
  Plugin.php
  behaviors/TranslatableModel.php
Labels: Status: Completed, Type: Enhancement

#625 only extend if it is not already extended
  Plugin.php
Labels: Status: Completed, Type: Maintenance
