Repository rainlab/translate-plugin, pull requests merged in 2020-06, with the labels that each got.

#580 fix regex when "|_" filter is followed by another filter
  classes/ThemeScanner.php
Labels: Status: Completed, Type: Maintenance

#577 Allows to export default locale
  models/MessageExport.php
  models/MessageImport.php
  tests/unit/models/ExportMessageTest.php
  tests/unit/models/ImportMessageTest.php
Labels: Type: Enhancement

#579 try locale without country before returning default translation
  models/Message.php
Labels: Status: Completed, Type: Enhancement
