Repository rainlab/translate-plugin, pull requests merged in 2020-10, with the labels that each got.

#600 Make plugin ready for Laravel 6 update
  .github/workflows/tests.yml
  .gitignore
  phpunit.xml
  routes.php
  tests/unit/behaviors/TranslatableCmsObjectTest.php
  tests/unit/behaviors/TranslatableModelTest.php
  tests/unit/behaviors/TranslatablePageTest.php
Labels: Status: Review Needed, Type: Maintenance

#607 simplify code to replace ml field types
  classes/EventRegistry.php
Labels: Status: Completed, Type: Maintenance

#608 add missing allowedExtensions in MLContent
  classes/MLContent.php
  models/MessageImport.php
  tests/unit/behaviors/TranslatablePageTest.php
  updates/builder_table_update_rainlab_translate_locales.php
  updates/update_messages_table.php
Labels: Status: Completed, Type: Maintenance

#609 fix migration on down() method
  updates/builder_table_update_rainlab_translate_locales.php
  updates/update_messages_table.php
Labels: Status: Completed, Type: Maintenance

#611 fix messages table layout on mobile
  assets/css/messages.css
  assets/less/messages.less
  controllers/messages/config_table.yaml
Labels: Status: Completed, Type: Maintenance

#605 mail templates/views can now be localized
  Plugin.php
  README.md
  classes/EventRegistry.php
Labels: Status: Completed, Type: Enhancement

#616 Translate new strings for TR language
  lang/tr/lang.php
Labels: Status: Accepted, Type: Maintenance

#617 Greek language added
  lang/gr/lang.php
Labels: Status: Completed, Type: Maintenance, hacktoberfest-accepted

#619 Update lang/pl/lang.php
  .github/workflows/tests.yml
  lang/pl/lang.php
Labels: Status: Revision Needed, Type: Maintenance
